import { expect, test } from "@playwright/test";
import { createHash } from "node:crypto";
import { initializeApp, getApps } from "firebase-admin/app";
import { getAuth } from "firebase-admin/auth";
import { getFirestore } from "firebase-admin/firestore";

test("admin creates a draft with original photos, itinerary and host, then publishes it", async ({ page, request }) => {
  test.setTimeout(120000);
  process.env.FIREBASE_AUTH_EMULATOR_HOST = "127.0.0.1:9099";
  process.env.FIRESTORE_EMULATOR_HOST = "127.0.0.1:8080";
  const projectId = "demo-bleetary";
  const app = getApps().find(a => a.name === "trip-editor-tests") ?? initializeApp({ projectId }, "trip-editor-tests");
  const auth = getAuth(app);
  const db = getFirestore(app);
  const stamp = Date.now();
  const email = `trip-admin-${stamp}@example.test`;
  const password = "TripAdmin!Pass1";
  const admin = await auth.createUser({ email, password, emailVerified: true, displayName: "Trip Admin" });
  await auth.setCustomUserClaims(admin.uid, { role: "admin" });
  const host = await auth.createUser({ email: `trip-host-${stamp}@example.test`, emailVerified: true, displayName: "Approved Test Host" });
  await auth.setCustomUserClaims(host.uid, { role: "host" });
  await db.collection("hostProfiles").doc(host.uid).set({ displayName: "Approved Test Host", status: "published", ownerUid: host.uid, bio: "An experienced local guide.", imagePath: null, tripsCount: 0, totalTravelersHosted: 0, averageRating: null, reviewCount: 0 });
  const unauthenticated = await request.post("/api/admin/trips", { headers: { origin: "http://127.0.0.1:3101" }, data: {} });
  expect(unauthenticated.status()).toBe(401);
  await page.goto("/login");
  await page.getByLabel("Email", { exact: true }).fill(email);
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page).toHaveURL("/admin");
  await page.getByRole("link", { name: "+ Add trip", exact: true }).click();
  await page.getByLabel("Trip title", { exact: true }).fill(`Victoria Falls ${stamp}`);
  await page.getByLabel("Trip introduction").fill("Explore Victoria Falls with an expert local host.");
  await page.getByLabel("Assigned host").selectOption(host.uid);
  await page.getByLabel("Destination name", { exact: true }).fill("Victoria Falls");
  await page.getByLabel("Country", { exact: true }).fill("Zimbabwe");
  await page.getByLabel("Two-letter country code").fill("ZW");
  await page.getByLabel("Region", { exact: true }).fill("Southern Africa");
  await page.getByLabel("Destination description").fill("Discover the waterfall and the surrounding national park.");
  await page.getByLabel("Start date", { exact: true }).fill("2028-06-10");
  await page.getByLabel("End date", { exact: true }).fill("2028-06-11");
  await page.getByLabel("Price per traveler (USD)").fill("1234.56");
  await page.getByLabel("Day 1 description").fill("Meet the host and explore the falls.");
  await page.getByLabel("Day 1 activities (one per line)").fill("Airport welcome\nWaterfall walk");
  await page.getByRole("button", { name: "+ Add itinerary day" }).click();
  await page.getByLabel("Day 2 title").fill("Safari and farewell");
  await page.getByLabel("Day 2 description").fill("Enjoy a morning safari before departing.");
  const original = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=", "base64");
  await page.getByLabel("Choose photos").setInputFiles({ name: "original.png", mimeType: "image/png", buffer: original });
  await expect(page.getByRole("link", { name: "Open full-quality original" })).toBeVisible();
  const originalUrl = await page.getByRole("link", { name: "Open full-quality original" }).getAttribute("href");
  const download = await request.get(originalUrl!);
  expect(download.ok()).toBeTruthy();
  expect(createHash("sha256").update(await download.body()).digest("hex")).toBe(createHash("sha256").update(original).digest("hex"));
  await page.getByRole("button", { name: "Save trip", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Trip saved as a draft" })).toBeVisible();
  const slug = `victoria-falls-${stamp}`;
  const trip = (await db.collection("trips").doc(slug).get()).data()!;
  expect(trip.hostUid).toBe(host.uid);
  expect(trip.basePriceCents).toBe(123456);
  const itinerary = (await db.collection("itineraries").doc(trip.itineraryId).get()).data()!;
  expect(itinerary.days).toHaveLength(2);
  expect(itinerary.days[0].activities[1].title).toBe("Waterfall walk");
  const result = await page.request.patch(`/api/admin/trips/${slug}/status`, { headers: { origin: "http://127.0.0.1:3101" }, data: { status: "published" } });
  expect(result.status(), await result.text()).toBe(200);
  expect((await db.collection("tripDepartures").doc(trip.managedDepartureId).get()).data()?.status).toBe("published");
  await page.goto(`/trips/${slug}`);
  await expect(page.getByRole("heading", { name: `Victoria Falls ${stamp}`, exact: true })).toBeVisible();
  await expect(page.getByText("Approved Test Host", { exact: true }).first()).toBeVisible();
  await expect(page.getByText("Safari and farewell")).toBeVisible();
});
